# Generated by Django 4.1.8 on 2023-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.IntegerField(default='241'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timeoftransaction',
            field=models.TimeField(default='16:07:20.441458'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mpin',
            field=models.BigIntegerField(default='4276'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.TextField(default='fnwysb'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.TextField(default='E6d05c'),
        ),
    ]
