# Generated by Django 4.1.8 on 2023-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.IntegerField(default='751'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timeoftransaction',
            field=models.TimeField(default='16:07:10.633963'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mpin',
            field=models.BigIntegerField(default='2508'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.TextField(default='jmrxnf'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.TextField(default='5bE416'),
        ),
    ]
