# Generated by Django 4.1.8 on 2023-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.IntegerField(default='310'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timeoftransaction',
            field=models.TimeField(default='16:09:30.160157'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mpin',
            field=models.BigIntegerField(default='7340'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.TextField(default='dtmqba'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.TextField(default='5D9e3c'),
        ),
    ]
