# Generated by Django 4.1.8 on 2023-05-06 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.BigIntegerField(null=True)),
                ('accountholder', models.TextField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('savings', models.FloatField(default=0.0)),
                ('tosave', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('accountnumber', models.BigIntegerField(default=0)),
                ('cardtype', models.CharField(max_length=50)),
                ('credit_balance', models.FloatField(default=0.0)),
                ('cardnumber', models.BigIntegerField(null=True)),
                ('cardholder', models.CharField(max_length=100)),
                ('cvv', models.IntegerField(default='956')),
                ('issueddatetime', models.DateField(default=datetime.date(2023, 5, 6))),
                ('expirydatetime', models.DateField(default=datetime.date(2023, 5, 6))),
                ('cardstatus', models.CharField(max_length=100)),
                ('verificationstatus', models.CharField(max_length=100)),
                ('cardid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoansDetails',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('applier_account_no', models.BigIntegerField(null=True)),
                ('tenure', models.IntegerField(blank=True, default=5, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('interest', models.FloatField(default=0.0)),
                ('totalPayment', models.FloatField(default=0.0)),
                ('monthlyPayment', models.FloatField(default=0.0)),
                ('loan_category', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('annual_income', models.IntegerField(default=0.0)),
                ('purpose_of_loan', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('applied_date', models.DateField(null=True, verbose_name=datetime.date(2023, 5, 6))),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('father_name', models.TextField(max_length=30)),
                ('mother_name', models.TextField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.TextField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('aadharnumber', models.BigIntegerField()),
                ('pannumber', models.TextField(max_length=10)),
                ('pincode', models.BigIntegerField()),
                ('dateofcreation', models.DateField(default=datetime.date(2023, 5, 6))),
                ('profile_pic', models.FileField(null=True, upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('toaccountnumber', models.BigIntegerField(null=True)),
                ('fromaccountnumber', models.BigIntegerField(null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('purpose', models.TextField(default='transfer')),
                ('status', models.TextField(null=True)),
                ('dateoftransaction', models.DateField(default='2023-05-06')),
                ('timeoftransaction', models.TimeField(default='16:06:53.892390')),
                ('location', models.TextField(null=True)),
                ('cardnumber', models.BigIntegerField(null=True)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.TextField(default='May')),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('account_no', models.BigIntegerField(default=0)),
                ('email', models.EmailField(default='hii@gmail.com', max_length=254)),
                ('role', models.TextField(default='user', null=True)),
                ('username', models.TextField(default='b0359e')),
                ('password', models.TextField(default='zrjsft')),
                ('mpin', models.BigIntegerField(default='2570')),
                ('verified_status', models.TextField(null=True)),
                ('account_status', models.TextField(null=True)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
