# Generated by Django 4.1.8 on 2023-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_carddetails_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='cvv',
            field=models.IntegerField(default='083'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timeoftransaction',
            field=models.TimeField(default='16:10:32.395997'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mpin',
            field=models.BigIntegerField(default='8709'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.TextField(default='ecudok'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.TextField(default='7ca1f3'),
        ),
    ]
